############################################################################
# Contest 2026 team 110 qiban sensor bridge - Makefile
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = qiban_sensor_bridge
PRIORITY  = SCHED_PRIORITY_DEFAULT
STACKSIZE = 8192
MODULE    = $(CONFIG_LVX_USE_DEMO_CONTEST2026_110_QIBAN_SENSOR_BRIDGE)

MAINSRC = qiban_sensor_bridge_main.c

include $(APPDIR)/Application.mk
