############################################################################
# Contest 2026 team 110 qiban WiFi bridge - Makefile
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = qiban_wifi_bridge
PRIORITY  = SCHED_PRIORITY_DEFAULT
STACKSIZE = 16384
MODULE    = $(CONFIG_LVX_USE_DEMO_CONTEST2026_110_QIBAN_WIFI_BRIDGE)

MAINSRC = qiban_wifi_bridge_main.c

include $(APPDIR)/Application.mk
