############################################################################
# Contest 2026 team 110 qiban music service - Makefile
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = qiban_music_service
PRIORITY  = SCHED_PRIORITY_DEFAULT
STACKSIZE = 24576
MODULE    = $(CONFIG_LVX_USE_DEMO_CONTEST2026_110_QIBAN_MUSIC_SERVICE)

MAINSRC = qiban_music_service_main.c

include $(APPDIR)/Application.mk
