############################################################################
# Contest 2026 team 110 qiban OTA service - Makefile
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = qiban_ota_service
PRIORITY  = SCHED_PRIORITY_DEFAULT
STACKSIZE = 16384
MODULE    = $(CONFIG_LVX_USE_DEMO_CONTEST2026_110_QIBAN_OTA_SERVICE)

MAINSRC = qiban_ota_service_main.c

include $(APPDIR)/Application.mk
