############################################################################
# Contest 2026 team 110 qiban vehicle service - Makefile
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = qiban_vehicle_service
PRIORITY  = SCHED_PRIORITY_DEFAULT
STACKSIZE = 4096
MODULE    = $(CONFIG_LVX_USE_DEMO_CONTEST2026_110_QIBAN_VEHICLE_SERVICE)

MAINSRC = qiban_vehicle_service_main.c

include $(APPDIR)/Application.mk
