############################################################################
# Contest 2026 team 110 qiban GPS receiver - Makefile
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = qiban_gps_receiver
PRIORITY  = SCHED_PRIORITY_DEFAULT
STACKSIZE = 8192
MODULE    = $(CONFIG_LVX_USE_DEMO_CONTEST2026_110_QIBAN_GPS_RECEIVER)

MAINSRC = qiban_gps_receiver_main.c

include $(APPDIR)/Application.mk
