#!/usr/bin/env bash
set -euo pipefail

QIBAN_AUDIO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
QIBAN_AUDIO_PYDEPS_DIR="${QIBAN_AUDIO_DIR}/.pydeps"
QIBAN_AUDIO_SITE_DIR="${QIBAN_AUDIO_DIR}/.venv_voice/site-packages"
QIBAN_AUDIO_CACHE_DIR="${QIBAN_AUDIO_DIR}/.voice_cache"
QIBAN_AUDIO_MODELS_DIR="${QIBAN_AUDIO_DIR}/models"

QIBAN_ASR_MODEL_URL_DEFAULT="https://alphacephei.com/vosk/models/vosk-model-small-cn-0.22.zip"
QIBAN_ASR_MODEL_DIR_DEFAULT="${QIBAN_AUDIO_MODELS_DIR}/asr/vosk-model-small-cn-0.22"

QIBAN_TTS_VOICE_DEFAULT="zh-CN-XiaoxiaoNeural"

export QIBAN_AUDIO_DIR
export QIBAN_AUDIO_PYDEPS_DIR
export QIBAN_AUDIO_SITE_DIR
export QIBAN_AUDIO_CACHE_DIR
export QIBAN_AUDIO_MODELS_DIR
export QIBAN_ASR_MODEL_URL="${QIBAN_ASR_MODEL_URL:-${QIBAN_ASR_MODEL_URL_DEFAULT}}"
export QIBAN_ASR_MODEL_DIR="${QIBAN_ASR_MODEL_DIR:-${QIBAN_ASR_MODEL_DIR_DEFAULT}}"
export QIBAN_TTS_VOICE="${QIBAN_TTS_VOICE:-${QIBAN_TTS_VOICE_DEFAULT}}"

if [[ -d "${QIBAN_AUDIO_SITE_DIR}" ]]; then
  export PYTHONPATH="${QIBAN_AUDIO_SITE_DIR}:${QIBAN_AUDIO_PYDEPS_DIR}${PYTHONPATH:+:${PYTHONPATH}}"
else
  export PYTHONPATH="${QIBAN_AUDIO_PYDEPS_DIR}${PYTHONPATH:+:${PYTHONPATH}}"
fi
